### ISSUE TITLE
[files app] file list spacing too big (files.css)

### ISSUE THREAD

**Issue by deMattin** [owncloud/core#15095]
The listing in files app has very much unused vertical space between the single entries.
As it is now, you can't see a lot files in webview without scrolling and I don't know any app or program, that uses so much line spacing.
I wonder, why this doesn't bother anyone else?

To fix this, I made some changes in files.css in my theme and reduced entry overall height from 52px to 35px.
This changes only reduce the spacing / line height and not the file previews or font height.
It works well and me and my co-users also like this view much more.
You see ~35% more files at once and need less scrolling and have a better overview of your files, if there are many of them in a folder.

**So I want to ask, what you think about to reduce the spacing in core for all users as default?**
I only would work out a pull request, if core team likes this.
But in fact I think, oC UI experts have a better way to fix and maintain such a change as I had to do it step by step and it was not easy to figure out all dependencies.

A second thing has been, that very much css-styles are not inherited.
"Normally" you only should have to change css of `<tr>` in filelist and all dependend css should scale.
There are many hard coded dependencies in css code.
But maybe I only haven't been able to see a better and more simple way ... ;)

I give you some screenshots to show, how it looks like:

**Default oC view**
![image](https://cloud.githubusercontent.com/assets/5565503/6769087/46c8f6ba-d08d-11e4-8b67-6f684778b03f.png)

**Changed oC view**
![image](https://cloud.githubusercontent.com/assets/5565503/6769082/f3d856f8-d08c-11e4-8a9e-8ae1bc2001b2.png)
![image](https://cloud.githubusercontent.com/assets/5565503/6769140/668d0b24-d08f-11e4-87e5-3bbebd6c0de0.png)

Here are my modifications in files.css to help anybody who likes this and if it won't been changed in core:
```css
/*  ----------------------------------------
 *  Dateilisting mit kleinerem Zeilenabstand
 *  ---------------------------------------- */

/* Höhe der Listenzeile
 * durch alle nachfolgenden Modifukationen, ist nur hier eine
 * Änderungen erforderlich, um die Zeilenhöhe zu vergrößern
 * 35px ist Minimum wegen Datei-Icons */
#filestable tbody tr {
	height: 35px;	}
#filestable tr {
	line-height: 0.0em;	}

/* Für Ordner Dropbereich bei Drag and Drop Aktion */
#filestable .uploadtext {
	padding: 0px 0px;	}

/* Dateinamen Drag and Drop Bereich */
#filestable td.filename .ui-draggable .ui-dropable {
	height: 34px;
	line-height: 34px;	}

/* Spalte Dateiname */
#filestable td.filename a.name {
	height: 34px;
	line-height: 34px;	}

/* Positionierung File-Icon */
#filestable td.filename .thumbnail {
	margin-top: 2px;	}

/* Positionierung Eingabefeld bei Dateinamenänderung */
#filestable td.filename input.filename {
	margin-top: 0px;	}

/* Spalte Dateigröße */
#filestable td.filesize .date {
	height: 32px;	}

/* Positionierung Favoriten-Stern bei Mouse-over */
#fileList a.action.action-favorite {
	padding: 8px 8px;	}

/* Positionierung Datei Selectbox */
#fileList tr td.filename>.selectCheckBox {
	margin: 22px 0 0px 32px;	}

/* Größe Datei Selectbox Bereich */
#fileList tr td.filename>.selectCheckBox + label {
	height: 32px;	}

/* Größe für Mouse-over Dateioptionen (Download, Share, ... */
#fileList tr td.filename a.name label {
	height: 34px;	}
#fileList a.action {
	line-height: 34px;	}

/* Positionierung Löschen-Papierkorb bei Mouse-over */
#fileList a.action.delete {
	padding: 7px 14px;	}

/* Abstand Fußzeile zur Dateiliste */
#filestable .summary {
	height: 36px;
	opacity: 1.0;
	color: #2980b9;	}
```
