### ISSUE TITLE
File synchronization buggy after having toggled encryption on and off

### ISSUE THREAD

**Issue by wikon** [owncloud/core#17634]
Some weeks ago we've had encryption enabled for testing but came to the conclusion that it might be safer to leave encryption disabled to avoid potential data loss (also because of some encryption issues described here).

Now we've upgraded to OC 8.1 (encryption has been disabled before) and some OC desktop clients are have trouble syncing files. Also in the web interface files are partially not accessible:

### Steps to reproduce
1. enable encryption under OC 8.0
2. disable encryption again (and decode files)
3. upgrade to OC 8.1
4. try uploading files with windows desktop client for OC (current version)

### Expected behaviour
Files are synchronized to the server

### Actual behaviour
Some errors like "Upload error" / "Download error" occur during the synchronization process.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache 2.4

**Database:** Postgresql

**PHP version:** 5.6

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:** Updated from older version

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - imprint: 0.2.5
 - search_lucene: 0.5.3
 - tasks: 0.7.0
 - templateeditor: 0.1
 - user_ldap: 0.6.1
Disabled:
 - admin_dependencies_chk
 - encryption
 - external
 - files_external
 - files_versions
 - gallery
 - provisioning_api
 - storagecharts2
 - user_external
 - user_webdavauth
```

**The content of config/config.php:**

```
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.
```

**Are you using external storage, if yes which one:** ---

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Owncloud Windows Client / Firefox

**Operating system:** Windows

#### Web server error log
```
n/a
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"AZdRB6TPH6SdHnhlJosO","remoteAddr":"1.2.3.4","app":"webdav","message":"Exception: {\"Message\":\"Module with id: OC_DEFAULT_MODULE does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(647): OC\\\\Encryption\\\\Manager->getEncryptionModule('OC_DEFAULT_MODU...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(218): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getEncryptionModule('files\\\/XXX\\\/Sock...')\\n#2 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->unlink('files\\\/XXX\\\/Sock...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(116): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/storage.php(89): OCA\\\\Files_Trashbin\\\\Storage->doDelete('files\\\/DART\\\/Sock...', 'unlink')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(149): OCA\\\\Files_Trashbin\\\\Storage->unlink('files\\\/DART\\\/Sock...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #33)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('XXX\\\/Socketmode...', Resource id #33, NULL)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/encryption\\\/manager.php\",\"Line\":159}","level":4,"time":"2015-07-14T06:17:25+00:00"}

```
