### ISSUE TITLE
Always »Token expired...« message on Chrome on iOS (News app)

### ISSUE THREAD

**Issue by cosenal** [owncloud/core#18891]
### Steps to reproduce
1. Open ownCloud on Chrome on iOS
2. Go to News app
3. Reload the page

### Expected behaviour
A compact view of the app should load

### Actual behaviour
The message »Token expired or app not enabled!« pops up and reloading the page doesn't help. 

### Server configuration
**Operating system**: Arch Linux

**Web server:** Apache/2.4.16 (Unix)

**Database:** SQLite

**PHP version:** 5.6.12 

**ownCloud version:** 8.2 pre alpha (git) aka *master*

**List of activated apps:**

```
Enabled:
  - files: 1.1.11
  - files_sharing: 0.6.3
  - files_texteditor: 0.4
  - files_versions: 1.0.6
  - mailsharenewsplugin: 0.0.1
  - news: 6.0.3
  - provisioning_api: 0.2
Disabled:
  - contacts
  - encryption
  - files_external
  - files_trashbin
  - mail
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc93c56bzuxh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "tchosky.pagekite.me",
            "192.168.1.128"
        ],
        "datadirectory": "\/srv\/http\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "sqlite3",
        "version": "8.2.0.4",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "app.mail.imaplog.enabled": true,
        "debug": true,
        "singleUser": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 45.0.2454.68

**Operating system:** iOS 8.4.1

#### Web server error log
```
nothing relevant here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"zGKTtUmY28N1bYL5o9sF","remoteAddr":"192.168.1.133","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-09-08T09:05:40+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/settings"}

```

#### Browser log
hmm, how do I F12 here? :)

Notes: previously opened in News repo, see https://github.com/owncloud/news/issues/854

cc: @BernhardPosselt @LukasReschke
