### ISSUE TITLE
Buttons on the Administration in APPS

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#21566]
Hi,

i be at moment in desighn of my theme, and have fellow me up,
to be the buttons not well in the APPS-Selector, like Multimedia,
Productivity and so on,
i have a black background and have desighn new buttons for it : 
```css
input[type="submit"], input[type="button"] { background: #9fa8ad;
  background-image: linear-gradient(to bottom, #9fa8ad, #3b3f42); background-image: -webkit-linear-gradient(top, #9fa8ad, #3b3f42);  
  background-image: -moz-linear-gradient(top, #9fa8ad, #3b3f42);  background-image: -ms-linear-gradient(top, #9fa8ad, #3b3f42);background-image: -o-linear-gradient(top, #9fa8ad, #3b3f42);
    border-radius: 7px; -webkit-border-radius: 7;  -moz-border-radius: 7;

  box-shadow: 4px 3px 3px #666666; -webkit-box-shadow: 4px 3px 3px #666666;  -moz-box-shadow: 4px 3px 3px #666666;
  font-family: VGAMedium;  color: #FFFFFF;  font-weight: 200; font-size: 20px;
  padding: 2px 2px 2px 2px;  border: 3px solid #828282 ; text-decoration: none;}

input[type="submit"], input[type="button"]:hover{ color:gold; background: #3b3f42; background-image: -webkit-linear-gradient(top, #3b3f42, #5d5f61);
  background-image: -moz-linear-gradient(top, #3b3f42, #5d5f61);  background-image: -ms-linear-gradient(top, #3b3f42, #5d5f61);
  background-image: -o-linear-gradient(top, #3b3f42, #5d5f61);  background-image: linear-gradient(to bottom, #3b3f42, #5d5f61);
  text-decoration: none;}

input[type="submit"], input[type="button"]:active{ color:green; background: #3b3f42;  background-image: -webkit-linear-gradient(top, #3b3f42, #5d5f61);
  background-image: -moz-linear-gradient(top, #3b3f42, #5d5f61);  background-image: -ms-linear-gradient(top, #3b3f42, #5d5f61);
  background-image: -o-linear-gradient(top, #3b3f42, #5d5f61);  background-image: linear-gradient(to bottom, #3b3f42, #5d5f61);
  -webkit-box-shadow: 0px 0px 0px #666666;  -moz-box-shadow: 0px 0px 0px #666666;
  box-shadow: 0px 0px 0px #666666;  text-decoration: none;}
  
```
and the normal buttons should be white like in the body {color:white;}
but it is green.. because the default it is normaly not activate it should be simple an normal link and not an activate button, activate it is if i press the button and hover if i with the pointer over it ..
or i be wrong ?
but on the other apps in owncloud works fine .. :\

There the fully theme : 
http://www.blackysgate.de/files/folder-root/owncloud

best regards
Blacky
