### ISSUE TITLE
Could not get node for path

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#22180]
Hello,
would delete some Files from my Owncloud drive, but i can´t delete these Files. i get this Error message:

Warning files Could not get node for path: \"Flugblatt EGO B\" : File with name Flugblatt EGO B could not be located 

This file still exsist. 
### Steps to reproduce
i don´t know how can i reproduce this.

### Expected behaviour
Can´t delete some files and Folders. Here are the damaged Folders. The same Folder with Content with correct names: **Bülent Ceylan Hanau** and **Kikeriki Theater Schlüchtern** are still present.

![damaged_folder](https://cloud.githubusercontent.com/assets/3295104/12872029/b694e3b8-cd95-11e5-8439-50e1d5063fc6.png)

and These the damaged file from the logfileentry.
![damaged_file](https://cloud.githubusercontent.com/assets/3295104/12872109/a4422e5c-cd98-11e5-98a9-70ea54b92025.png)

### Actual behaviour
When i try to delete these Folders/Files there are back after refresh the Browser.
When i click on these damaged Folder, it open this URL: https://cloud.domain.tld/index.php/apps/files?dir=%2F

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**

```
Enabled:                                                                                                                               
  - activity: 2.1.3                                                                                                                    
  - bookmarks: 0.6                                                                                                                     
  - calendar: 0.8.1                                                                                                                    
  - contacts: 0.5.0.0                                                                                                                  
  - documents: 0.11.1                                                                                                                  
  - files: 1.2.0                                                                                                                       
  - files_external: 0.3.0                                                                                                              
  - files_pdfviewer: 0.7                                                                                                               
  - files_sharing: 0.7.0                                                                                                               
  - files_texteditor: 2.0                                                                                                              
  - files_trashbin: 0.7.0                                                                                                              
  - files_versions: 1.1.0                                                                                                              
  - files_videoviewer: 0.1.3                                                                                                           
  - files_videoviewerplus: 0.0.1                                                                                                       
  - firstrunwizard: 1.1                                                                                                                
  - gallery: 14.2.0                                                                                                                    
  - music: 0.3.8                                                                                                                       
  - news: 7.1.1                                                                                                                        
  - notes: 2.0.0                                                                                                                       
  - notifications: 0.1.0                                                                                                               
  - ocdownloader: 1.5                                                                                                                  
  - ownbackup: 0.3.7                                                                                                                   
  - provisioning_api: 0.3.0                                                                                                            
  - tasks: 0.8.1                                                                                                                       
  - templateeditor: 0.1                                                                                                                
Disabled:                                                                                                                              
  - encryption                                                                                                                         
  - external                                                                                                                           
  - files_w2g                                                                                                                          
  - galleryplus                                                                                                                        
  - ownnote                                                                                                                            
  - user_external                                                                                                                      
  - user_ldap
```

**The content of config/config.php:**

```
<?php                                                                                                                                  
$CONFIG = array (                                                                                                                      
  'instanceid' => 'ocpsovzwa7ww',                                                                                                      
  'passwordsalt' => 'eZCC32Qq0GjmKwtA2pPvk0gjNjQxF2',                                                                                  
  'secret' => 'mmJaAUqJEB2iiP15LiXoGS3iuWsLnOOz1eJAkh5QlrdFf7Q3',                                                                      
  'trusted_domains' =>                                                                                                                 
  array (                                                                                                                              
    0 => '81.169.130.87',                                                                                                              
    1 => 'cloud.domain.tld',                                                                                                    
    2 => 'serverxxxx.stratoserver.net',                                                                                                  
  ),                                                                                                                                   
  'datadirectory' => '/home/owncloud/data',                                                                                            
  'overwrite.cli.url' => 'http://12.23.45/owncloud',                                                                              
  'dbtype' => 'mysql',                                                                                                                 
  'version' => '8.2.2.2',                                                                                                              
  'dbname' => 'owncloud',                                                                                                              
  'dbhost' => 'localhost',                                                                                                             
  'dbtableprefix' => 'oc_',                                                                                                            
  'dbuser' => 'owncloud',                                                                                                              
  'dbpassword' => 'passwd remove',                                                                                                          
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',                                                                               
  'memcached_servers' =>                                                                                                               
  array (                                                                                                                              
    0 =>                                                                                                                               
    array (                                                                                                                            
      0 => 'localhost',                                                                                                                
      1 => 11211,                                                                                                                      
    ),                                                                                                                                 
    1 =>                                                                                                                               
    array (                                                                                                                            
      0 => 'cloud.domain.tld',                                                                                                  
      1 => 11211,                                                                                                                      
    ),                                                                                                                                 
  ),                                                                                                                                   
  'logtimezone' => 'Europe/Berlin',                                                                                                    
  'installed' => true,                                                                                                                 
  'loglevel' => 2,                                                                                                                     
);      
```
**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Chrome, Firefox, all the same issue
**Operating system:**

#### Web server error log
```
[Sun Feb 07 04:30:01.446149 2016] [ssl:warn] [pid 8327] AH01909: RSA certificate configured for h2530151.stratoserver.net:443 does NOT 
include an ID which matches the server name                                                                                            
[Sun Feb 07 04:30:01.446357 2016] [mpm_prefork:notice] [pid 8327] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 OpenSSL/1.0.1f c
onfigured -- resuming normal operations                                                                                                
[Sun Feb 07 04:30:01.446367 2016] [core:notice] [pid 8327] AH00094: Command line: '/usr/sbin/apache2'                                  
[Sun Feb 07 09:41:35.403053 2016] [authz_core:error] [pid 10203] [client 81.169.130.87:58512] AH01630: client denied by server configur
ation: /var/www/owncloud/data/htaccesstest.txt                                                                                         
[Sun Feb 07 12:10:07.431524 2016] [authz_core:error] [pid 14693] [client 81.169.130.87:44119] AH01630: client denied by server configur
ation: /var/www/owncloud/data/htaccesstest.txt
```
####access.log
```
5.10.188.170 - - [07/Feb/2016:12:37:50 +0100] "GET /index.php/apps/activity/activities/fetch?page=1&filter=filter&objectid=22294&object
type=files HTTP/1.1" 200 899 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko"                           
5.10.188.170 - - [07/Feb/2016:12:37:52 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2FBildersammlung%2FBilder+von+Veranstaltung
en%2FB&sort=name&sortdirection=asc HTTP/1.1" 404 734 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko"   
5.10.188.170 - - [07/Feb/2016:12:37:53 +0100] "GET /index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 20
0 11983 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko"                                                
5.10.188.170 - - [07/Feb/2016:12:37:53 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 993 "-" "Mozill
a/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko" 
 
```

#### ownCloud log (data/owncloud.log)
```
Warning files Could not get node for path: \"Flugblatt EGO B\" : File with name Flugblatt EGO B could not be located 2016-02-07T12:10:04+01:00 
Warning files Could not get node for path: \"Flugblatt EGO B\" : File with name Flugblatt EGO B could not be located 2016-02-07T09:41:32+01:00 
Warning files Could not get node for path: \"Flugblatt EGO B\" : File with name Flugblatt EGO B could not be located 


```
