### ISSUE TITLE
ownCloud 9 occ files:scan incredibly slow

### ISSUE THREAD

**Issue by fireba11** [owncloud/core#23779]
### Steps to reproduce
1. run sudo -u www-data php occ files:scan --all
2. wait far longer than reasonable
3. environment: physical root server, load around 0,2
### Expected behaviour

files scan (with that amount of files) would be expected to take a couple seconds, a couple minutes if double-checking mime-types is involved
### Actual behaviour

3k folders, 32k files => takes over 1 hour (!)
according to my munin heaps of uncached mysql querries
for relation: creating the daily dumps of ALL my mysql databases (0,5GB as .gz) takes 6 minutes
### Server configuration

**Operating system**:
debian 8.3
**Web server:**
apache 2.4.10-10+deb8u4
**Database:**
mysql 14.14
**PHP version:**
5.6.17-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated (removed everythin except config.php and data folder, then installed with web installer
**Where did you install ownCloud from:**
https://download.owncloud.com/download/community/setup-owncloud.php
**Signing status (ownCloud 9.0 and above):**
# Results

```
- core
    - INVALID_HASH
        - .htaccess
        - .user.ini
```

**List of activated apps:**

```
Enabled:

    activity: 2.2.1
    calendar: true
    comments: 0.2
    contacts: true
    dav: 0.1.5
    federatedfilesharing: 0.1.0
    federation: 0.0.4
    files: 1.4.4
    files_external: 0.5.2
    files_pdfviewer: 0.8
    files_sharing: 0.9.1
    files_texteditor: 2.1
    files_trashbin: 0.8.0
    files_versions: 1.2.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 14.5.0
    notifications: 0.2.3
    provisioning_api: 0.4.1
    systemtags: 0.2
    templateeditor: 0.1
    updatenotification: 0.1.0

Disabled:
    encryption
    external
    user_external
    user_ldap
```

**The content of config/config.php:**

``` json
{
    "system": {
        "instanceid": "***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/clients\/client1\/web43\/web\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "c1owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "check_for_working_webdav": false,
        "theme": "",
        "trusted_domains": [
            "owncloud.somedomain.com",
            "owncloud.somedomain.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "somedomain.com",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,90",
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
FF 45.0.1
**Operating system:**
Win10
