### ISSUE TITLE
The apps-display page under the admins tab in settings page makes all the apps disappear if resolution is lesser than 768px (mobile view)

### ISSUE THREAD

**Issue by noveens** [owncloud/core#27229]
### Steps to reproduce
1. Go to the apps page in setting menu (under the admin bar)
2. decrease the resolution of the page to lesser than 768px

### Expected behaviour
Tell us what should happen
Apps should be displayed

### Actual behaviour
Tell us what happens instead
Apps not displayed

### GIF:
![desktop-animation](https://cloud.githubusercontent.com/assets/23054294/23258368/f392b2ce-f9ed-11e6-83d0-ea90b94b955d.gif)

### Server configuration
**Operating system**:
Ubuntu 16.10

**Web server:**
Apache

**Database:**
Sqlite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.0

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
GitHub's core repository

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: true
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - testing
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocr5wxqbp599",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "sqlite3",
        "version": "10.0.0.4",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:**
/core/data

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Google chrome stable & Mozilla Firefox

**Operating system:**
Ubuntu 16.10

#### Web server error log
```
None Required
```

#### ownCloud log (data/owncloud.log)
```
None Required
```

#### Browser log
```
None Required
```

@tomneedham please look into this.
