### ISSUE TITLE
Mail Templates Settings Are Broken after 9.1 -> 10.0 Upgrade

### ISSUE THREAD

**Issue by keassol** [owncloud/core#27759]
### Steps to reproduce
1. Nav to Setting -> Admin -General
2. Dropdown "Please choose a template
3. Get Dialog Error "Could not load template... Template Not Editable"

### Expected behaviour
Form should fill with the current template text

### Actual behaviour
Error message

### Server configuration
**Operating system**
Ubuntu 14.04

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
MariaDB 10.1.22

**PHP version:**
PHP 5.6.30-10+deb.sury.org~trusty+2

**ownCloud version:** (see ownCloud admin page)
10.0.0.12

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
ubuntu packages

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "XXXXXXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXX"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "XXXXXXX",
        "mail_smtpmode": "php",
        "mail_domain": "XXXXXXX",
        "theme": "",
        "maintenance": false,
        "loglevel": 8,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud8",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "\/owncloud",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APC"
    }
}
```

**List of activated apps:**

```
Enabled:

    activity: 2.3.3
    calendar: true
    comments: 0.3.0
    configreport: 0.1.1
    contacts: true
    dav: 0.2.8
    external: 1.2
    federatedfilesharing: 0.3.0
    federation: 0.1.0
    files: 1.5.1
    files_external: 0.7.0
    files_pdfviewer: 0.8.1
    files_sharing: 0.10.0
    files_texteditor: 2.1
    files_trashbin: 0.9.0
    files_versions: 1.3.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 15.0.0
    grauphel: 0.6.4
    market: 0.1.0
    notifications: 0.3.0
    provisioning_api: 0.5.0
    systemtags: 0.3.0
    templateeditor: 0.1
    updatenotification: 0.2.1
    Disabled:
    encryption
    example-theme
    files_antivirus
    user_external

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 53.0

**Operating system:**
Win 7 Pro up to date

#### Web server error log
```
none
```

#### ownCloud log (data/owncloud.log)
```
none
```

#### Browser log
```
Insert your browser log here, this could for example include:

JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542

```
