### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by andlinger** [owncloud/core#32462]
### Expected behaviour
No browser/js errors

### Actual behaviour
Missing jQuery on Login Page
![image](https://user-images.githubusercontent.com/1436448/44669401-14d55200-aa20-11e8-8096-8489264be795.png)

Source code of the login page: https://pastebin.com/Jx3cWR5b





### Server configuration
**Operating system**: RHEL 7

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.27

**ownCloud version:** 10.0.9.5

**Updated from an older ownCloud or fresh install:** Upgraded from older version 9.1.6

**Where did you install ownCloud from:** Git branch

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

Unable to login


**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

https://pastebin.com/J5FV4m3B

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
```
Enabled:                                                                                                                                                                                                                                                
  - dav: 0.3.2                                                                                                                                                                                                                                          
  - federatedfilesharing: 0.3.1                                                                                                                                                                                                                         
  - files: 1.5.1                                                                                                                                                                                                                                        
  - files_external: 0.7.1                                                                                                                                                                                                                               
  - files_sharing: 0.10.1                                                                                                                                                                                                                               
  - provisioning_api: 0.5.0                                                                                                                                                                                                                             
  - systemtags: 0.3.0                                                                                                                                                                                                                                   
  - updatenotification: 0.2.1                                                                                                                                                                                                                           
Disabled:                                                                                                                                                                                                                                               
  - comments                                                                                                                                                                                                                                            
  - encryption                                                                                                                                                                                                                                          
  - federation                                                                                                                                                                                                                                          
  - files_trashbin                                                                                                                                                                                                                                      
  - files_versions                                                                                                                                                                                                                                      
  - testing   
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox, Chrome, Edge (always newest)

**Operating system:** Window 10, macOS
