### ISSUE TITLE
In stable10 .drone.yml 2 there are ceph services sections

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33719]
In ``stable10`` ``.drone.yml`` there are 2 ``ceph:`` sections in ``services:``

```
services:

  ceph:
    image: owncloudci/ceph
    pull: true
    environment:
      - KEYSTONE_PUBLIC_PORT=5034
      - KEYSTONE_ADMIN_USER=test
      - KEYSTONE_ADMIN_PASS=testing
      - KEYSTONE_ADMIN_TENANT=testtenant
      - KEYSTONE_ENDPOINT_REGION=testregion
      - KEYSTONE_SERVICE=testceph
      - OSD_SIZE=500
    when:
      matrix:
        OBJECTSTORE: swift
```

and further down:
```
  ceph:
    image: owncloudci/ceph
    pull: true
    environment:
      - KEYSTONE_PUBLIC_PORT=5034
      - KEYSTONE_ADMIN_USER=test
      - KEYSTONE_ADMIN_PASS=testing
      - KEYSTONE_ADMIN_TENANT=testtenant
      - KEYSTONE_ENDPOINT_REGION=testregion
      - KEYSTONE_SERVICE=testceph
      - OSD_SIZE=500
    when:
      matrix:
        FILES_EXTERNAL_TYPE: swift
```

I suspect 2 different changes were added at similar times, putting ``ceph`` stuff in place. Because the 2 sections were added at top and bottom of the ``services:`` list, ``git`` did not see any merge conflicts.

PR https://github.com/owncloud/core/pull/30775/files
PR https://github.com/owncloud/core/pull/30767/files
