### ISSUE TITLE
Generate API docs and upload them to our docs page

### ISSUE THREAD

**Issue by tboerger** [owncloud/core#33838]
In the past we had a Jenkins job that generated the API docs from the core and added it to the generated Docker container, since we moved the docs away from Jenkins into Drone and since we are not deploying a Docker container anymore the process got to change as well.

Within Jenkins we built the API like that, but I would like to avoid using my webhippie images as part of the core pipeline:

```
docker run --rm -t \
  -u $(id -u):$(id -g) \
  -v $(pwd):/srv/app \
  -w /srv/app \
  webhippie/phpdoc:latest \
  phpdoc \
  project:run \
  --directory=source/lib/public \
  --target=build \
  --title=ownCloud-API
```

I would like to get a make target as part of the core repository which generates the API documentation with phpdoc, I guess we could add phpdoc as a dev dependency to this repository.

After adding a make target for that we could build and upload the API docs within two Drone steps on every merge/push to the master branch. The Drone pipeline definition could be as simple as this:

```
  generate-phpdoc:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make phpdoc
    when:
      event: [ push ]
      branch: [ master ]
      matrix:
        TEST_SUITE: phpdoc

  upload-phpdoc:
    image: plugins/s3-sync:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: uploads
    endpoint: https://doc.owncloud.com
    path_style: true
    source: phpdoc/
    target: /phpdoc
    delete: true
    when:
      local: false
      event: [ push ]
      branch: [ master ]
      matrix:
        TEST_SUITE: phpdoc
```

I will upload the API documentation manually now, but this process should be automated to keep the docs really up to date.
