### ISSUE TITLE
Integrity check not detecting missing files properly

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34075]
### Steps

1. Setup ownCloud 10.1.0 beta
1. Download the 1.0.2 tarball of https://marketplace.owncloud.com/apps/files_primary_s3 (note that the file is corrupt due to https://github.com/owncloud/files_primary_s3/issues/171
1. Install with `occ market:install --local files_primary_s3-1.0.2.tar.gz`.
1. Run `./occ integrity:check-app files_primary_s3`

### Expected result
Error related to the broken path "vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware."

### Actual result
No output, no error.

Note that if you modify the above file it suddenly appears in the output:
```
  - FILE_MISSING:
    - vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware.php:
      - expected: f4db33875a63b4e23f65896c53106e759eaebc98774834f03b202aa7a556005cd0002f2b574767c07c47ada8829be51d990d99d6dd8b0f43d3e8c4c97d584f9a
      - current: 
  - EXTRA_FILE:
    - vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ApiCallAttemptMonitoringMiddleware.:
      - expected: 
      - current: 1d54d2832e567fe62c6cba4318aa75ab48318c7b08164bef30822fd6e43b9bf2eb2d60dfc449d6c9b75597136c06b0d62b203554f8d900a9f29cff569952b2a8
```
