### ISSUE TITLE
HTTP/1.1 418 I'm a teapot response to a REPORT request

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#38463]
### Steps to reproduce
1. favourite a file or folder
2. send a REPORT request: ` curl -u admin:admin -X REPORT http://localhost/owncloud-core/remote.php/dav/files/admin -d '<?xml version="1.0" encoding="UTF-8"?> <oc:filter-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns"> <oc:filter-rules> <oc:favorite>1</oc:favorite> </oc:filter-rules> </oc:filter-files>' | xmllint --format -`

### Expected behaviour
`d:status` should have a useful output

### Actual behaviour
`<d:status>HTTP/1.1 418 I'm a teapot</d:status>`

### further information
adding `<a:prop><oc:favorite/></a:prop>` to the request gives `<d:status>HTTP/1.1 200 OK</d:status>`

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.4
**ownCloud version:** (see ownCloud admin page)
10.6.1alpha (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.17.0.1"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "version": "10.6.1.0",
        "logtimezone": "UTC",
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "loglevel": "1",
        "log_type": "owncloud",
        "theme": "",
        "sharing.federation.allowHttpFallback": true,
        "files_external_allow_create_new_local": "true",
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "oc4kyqahfanl",
        "enable_previews": true,
        "apps_paths": [
            {
                "path": "\/home\/artur\/www\/owncloud-core\/apps",
                "url": "apps",
                "writable": true
            },
            {
                "path": "\/home\/artur\/www\/owncloud-core\/apps2",
                "url": "apps2",
                "writable": true
            }
        ],
        "csrf.disabled": true,
        "maintenance": false,
        "cors.allowed-domains": [
            "http:\/\/localhost\/owncloud-web\/dist",
            "http:\/\/localhost:9876",
            "http:\/\/localhost:9100"
        ],
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "default_language": "en",
        "dav.enable.tech_preview": true,
        "dbtype": "mysql",
        "dbname": "owncloud_20201215",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "grace_period.demo_key.show_popup": false,
        "openid-connect": {
            "provider-url": "https:\/\/localhost:9130",
            "client-id": "web",
            "loginButtonName": "OpenId Connect @ Konnectd",
            "insecure": true
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "debug": true,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/apps\/testing\/data\/webUISkeleton"
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments:
    - Version: 0.3.0
    - Path: /home/artur/www/owncloud-core/apps/comments
  - dav:
    - Version: 0.6.0
    - Path: /home/artur/www/owncloud-core/apps/dav
  - diagnostics:
    - Version: 0.1.4
    - Path: /home/artur/www/owncloud-core/apps/diagnostics
  - enterprise_key:
    - Version: 0.3.0
    - Path: /home/artur/www/owncloud-core/apps/enterprise_key
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /home/artur/www/owncloud-core/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /home/artur/www/owncloud-core/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /home/artur/www/owncloud-core/apps/files
  - files_external:
    - Version: 0.7.1
    - Path: /home/artur/www/owncloud-core/apps/files_external
  - files_sharing:
    - Version: 0.14.0
    - Path: /home/artur/www/owncloud-core/apps/files_sharing
  - files_texteditor:
    - Version: 2.3.0
    - Path: /home/artur/www/owncloud-core/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /home/artur/www/owncloud-core/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /home/artur/www/owncloud-core/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /home/artur/www/owncloud-core/apps/firstrunwizard
  - graphapi:
    - Version: 0.2.0
    - Path: /home/artur/www/owncloud-core/apps/graphapi
  - notifications:
    - Version: 0.5.0
    - Path: /home/artur/www/owncloud-core/apps/notifications
  - oauth2:
    - Version: 0.4.3
    - Path: /home/artur/www/owncloud-core/apps/oauth2
  - provisioning_api:
    - Version: 0.5.0
    - Path: /home/artur/www/owncloud-core/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /home/artur/www/owncloud-core/apps/systemtags
  - testing:
    - Version: 0.1.0
    - Path: /home/artur/www/owncloud-core/apps/testing
  - updatenotification:
    - Version: 0.2.1
    - Path: /home/artur/www/owncloud-core/apps/updatenotification
Disabled:
  - activity:
    - Path: /home/artur/www/owncloud-core/apps/activity
  - admin_audit:
    - Path: /home/artur/www/owncloud-core/apps/admin_audit
  - brute_force_protection:
    - Path: /home/artur/www/owncloud-core/apps/brute_force_protection
  - customgroups:
    - Path: /home/artur/www/owncloud-core/apps/customgroups
  - data_exporter:
    - Path: /home/artur/www/owncloud-core/apps/data_exporter
  - files_antivirus:
    - Path: /home/artur/www/owncloud-core/apps/files_antivirus
  - files_classifier:
    - Path: /home/artur/www/owncloud-core/apps/files_classifier
  - files_lifecycle:
    - Path: /home/artur/www/owncloud-core/apps/files_lifecycle
  - files_primary_s3:
    - Path: /home/artur/www/owncloud-core/apps/files_primary_s3
  - firewall:
    - Path: /home/artur/www/owncloud-core/apps/firewall
  - guests:
    - Path: /home/artur/www/owncloud-core/apps/guests
  - openidconnect:
    - Path: /home/artur/www/owncloud-core/apps/openidconnect
  - password_policy:
    - Path: /home/artur/www/owncloud-core/apps/password_policy
  - ransomware_protection:
    - Path: /home/artur/www/owncloud-core/apps/ransomware_protection
  - richdocuments:
    - Path: /home/artur/www/owncloud-core/apps/richdocuments
  - sharepoint:
    - Path: /home/artur/www/owncloud-core/apps/sharepoint
  - systemtags_management:
    - Path: /home/artur/www/owncloud-core/apps/systemtags_management
  - twofactor_totp:
    - Path: /home/artur/www/owncloud-core/apps/twofactor_totp
  - user_ldap:
    - Path: /home/artur/www/owncloud-core/apps/user_ldap
  - windows_network_drive:
    - Path: /home/artur/www/owncloud-core/apps/windows_network_drive
  - wopi:
    - Path: /home/artur/www/owncloud-core/apps/wopi
  - workflow:
    - Path: /home/artur/www/owncloud-core/apps/workflow
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
```
127.0.0.1 - admin [04/Mar/2021:10:18:26 +0545] "REPORT /owncloud-core/remote.php/dav/files/admin HTTP/1.1" 207 1275 "-" "curl/7.68.0"
```

#### ownCloud log (data/owncloud.log)
no output
