### ISSUE TITLE
No files displayed in WEBUI

### ISSUE THREAD

**Issue by misse** [owncloud/core#38615]
### Steps to reproduce
1. Deploy owncloud 10.5 with docker-compose
2. Upload files with a desktop client
3. Log in to web ui

### Expected behaviour
I expect to see my uploaded files

### Actual behaviour
The list of files is just white, nothing is listed and the developer console hints that the UI fails to identify my user id.

### Server configuration
**Operating system**:
Ubuntu 18.04 running docker
**Web server:**
Apache2
**Database:**
Mariadb
**PHP version:**
7.4.3
**ownCloud version:** (see ownCloud admin page)
10.7.0.4
**Updated from an older ownCloud or fresh install:**
10.5
**Where did you install ownCloud from:**
Docker hub
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**
https://oc.misse.org/s/xO7qrRozdqPeQm0

**List of activated apps:**

```
Enabled:
  - activity:
    - Version: 2.6.0
    - Path: /var/www/owncloud/apps/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.7.1
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.4
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 0.11.2
    - Path: /var/www/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.3.0
    - Path: /var/www/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Version: 0.5.2
    - Path: /var/www/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/owncloud/apps/templateeditor
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification
  - user_ldap:
    - Version: 0.15.2
    - Path: /var/www/owncloud/apps/user_ldap
Disabled:
  - admin_audit:
    - Path: /var/www/owncloud/apps/admin_audit
  - announcementcenter:
    - Path: /var/www/owncloud/apps/announcementcenter
  - customgroups:
    - Path: /var/www/owncloud/apps/customgroups
  - encryption:
    - Path: /var/www/owncloud/apps/encryption
  - enterprise_key:
    - Path: /var/www/owncloud/apps/enterprise_key
  - external:
    - Path: /var/www/owncloud/apps/external
  - files_antivirus:
    - Path: /var/www/owncloud/apps/files_antivirus
  - files_classifier:
    - Path: /var/www/owncloud/apps/files_classifier
  - files_external_dropbox:
    - Path: /var/www/owncloud/apps/files_external_dropbox
  - files_external_ftp:
    - Path: /var/www/owncloud/apps/files_external_ftp
  - files_ldap_home:
    - Path: /var/www/owncloud/apps/files_ldap_home
  - files_lifecycle:
    - Path: /var/www/owncloud/apps/files_lifecycle
  - firewall:
    - Path: /var/www/owncloud/apps/firewall
  - graphapi:
    - Path: /var/www/owncloud/apps/graphapi
  - guests:
    - Path: /var/www/owncloud/apps/guests
  - metrics:
    - Path: /var/www/owncloud/apps/metrics
  - oauth2:
    - Path: /var/www/owncloud/apps/oauth2
  - openidconnect:
    - Path: /var/www/owncloud/apps/openidconnect
  - password_policy:
    - Path: /var/www/owncloud/apps/password_policy
  - ransomware_protection:
    - Path: /var/www/owncloud/apps/ransomware_protection
  - sharepoint:
    - Path: /var/www/owncloud/apps/sharepoint
  - systemtags_management:
    - Path: /var/www/owncloud/apps/systemtags_management
  - theme-enterprise:
    - Path: /var/www/owncloud/apps/theme-enterprise
  - user_external:
    - Path: /var/www/owncloud/apps/user_external
  - user_shibboleth:
    - Path: /var/www/owncloud/apps/user_shibboleth
  - windows_network_drive:
    - Path: /var/www/owncloud/apps/windows_network_drive
  - wopi:
    - Path: /var/www/owncloud/apps/wopi
  - workflow:
    - Path: /var/www/owncloud/apps/workflow

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Google Chrome  89.0.4389.114
**Operating system:**
Mac OS 10.14.3
Windows 10 1903
#### Web server error log
```
owncloud_1  | 2021-04-01T10:33:32.613384097Z Creating volume folders...
owncloud_1  | 2021-04-01T10:33:32.621456717Z Creating hook folders...
owncloud_1  | 2021-04-01T10:33:32.632843193Z Waiting for MySQL...
owncloud_1  | 2021-04-01T10:33:32.729870993Z services are ready!
owncloud_1  | 2021-04-01T10:33:32.730878736Z Waiting for Redis...
owncloud_1  | 2021-04-01T10:33:32.738008537Z services are ready!
owncloud_1  | 2021-04-01T10:33:32.738689996Z Removing custom folder...
owncloud_1  | 2021-04-01T10:33:32.867127240Z Linking custom folder...
owncloud_1  | 2021-04-01T10:33:32.871772347Z Removing config folder...
owncloud_1  | 2021-04-01T10:33:32.873127222Z Linking config folder...
owncloud_1  | 2021-04-01T10:33:32.874204252Z Writing config file...
owncloud_1  | 2021-04-01T10:33:33.783828912Z Fixing base perms...
owncloud_1  | 2021-04-01T10:33:34.526079432Z Fixing data perms...
owncloud_1  | 2021-04-01T10:33:39.082794767Z Fixing hook perms...
owncloud_1  | 2021-04-01T10:33:43.070174058Z Upgrading server database...
owncloud_1  | 2021-04-01T10:33:43.215342211Z ownCloud or one of the apps require upgrade - only a limited number of commands are available
owncloud_1  | 2021-04-01T10:33:43.215379677Z You may use your browser or the occ upgrade command to do the upgrade
owncloud_1  | 2021-04-01T10:33:43.225556584Z 2021-04-01T10:33:43+00:00 Set log level to debug
owncloud_1  | 2021-04-01T10:33:43.699831185Z 2021-04-01T10:33:43+00:00 Repair step: Upgrade app code from the marketplace
owncloud_1  | 2021-04-01T10:33:43.743832477Z 2021-04-01T10:33:43+00:00 Repair info: Using market to update existing apps
owncloud_1  | 2021-04-01T10:33:43.743969215Z 2021-04-01T10:33:43+00:00 Repair info: Attempting to update the following existing compatible apps from market: activity, comments, configreport, dav, federatedfilesharing, federation, fil
es, files_external, files_mediaviewer, files_pdfviewer, files_sharing, files_texteditor, files_trashbin, files_versions, firstrunwizard, market, notifications, provisioning_api, systemtags, templateeditor, updatenotification, user_ldap
owncloud_1  | 2021-04-01T10:33:43.743991450Z 2021-04-01T10:33:43+00:00 Repair info: Fetching app from market: activity
owncloud_1  | 2021-04-01T10:33:44.299425344Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.299459779Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: comments
owncloud_1  | 2021-04-01T10:33:44.300477882Z 2021-04-01T10:33:44+00:00 Repair info: App (comments) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.300666794Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: configreport
owncloud_1  | 2021-04-01T10:33:44.301037857Z 2021-04-01T10:33:44+00:00 Repair info: App (configreport) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.301210815Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: dav
owncloud_1  | 2021-04-01T10:33:44.301615050Z 2021-04-01T10:33:44+00:00 Repair info: App (dav) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.301793286Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: federatedfilesharing
owncloud_1  | 2021-04-01T10:33:44.302167878Z 2021-04-01T10:33:44+00:00 Repair info: App (federatedfilesharing) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.302399275Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: federation
owncloud_1  | 2021-04-01T10:33:44.302765992Z 2021-04-01T10:33:44+00:00 Repair info: App (federation) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.302965513Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files
owncloud_1  | 2021-04-01T10:33:44.303391442Z 2021-04-01T10:33:44+00:00 Repair info: App (files) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.303627893Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_external
owncloud_1  | 2021-04-01T10:33:44.304059279Z 2021-04-01T10:33:44+00:00 Repair info: App (files_external) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.304144902Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_mediaviewer
owncloud_1  | 2021-04-01T10:33:44.304673408Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.304873048Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_pdfviewer
owncloud_1  | 2021-04-01T10:33:44.305364487Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.305599947Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_sharing
owncloud_1  | 2021-04-01T10:33:44.306098265Z 2021-04-01T10:33:44+00:00 Repair info: App (files_sharing) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.306114041Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_texteditor
owncloud_1  | 2021-04-01T10:33:44.306729135Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.306747033Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_trashbin
owncloud_1  | 2021-04-01T10:33:44.307276456Z 2021-04-01T10:33:44+00:00 Repair info: App (files_trashbin) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.307292507Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_versions
owncloud_1  | 2021-04-01T10:33:44.308015113Z 2021-04-01T10:33:44+00:00 Repair info: App (files_versions) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.308034135Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: firstrunwizard
owncloud_1  | 2021-04-01T10:33:44.308577276Z 2021-04-01T10:33:44+00:00 Repair info: App (firstrunwizard) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.308651457Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: market
owncloud_1  | 2021-04-01T10:33:44.310390379Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.310422273Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: notifications
owncloud_1  | 2021-04-01T10:33:44.311260074Z 2021-04-01T10:33:44+00:00 Repair info: App (notifications) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.311278501Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: provisioning_api
owncloud_1  | 2021-04-01T10:33:44.311931835Z 2021-04-01T10:33:44+00:00 Repair info: App (provisioning_api) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.311947684Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: systemtags
owncloud_1  | 2021-04-01T10:33:44.312912187Z 2021-04-01T10:33:44+00:00 Repair info: App (systemtags) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.312951806Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: templateeditor
owncloud_1  | 2021-04-01T10:33:44.313846963Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.313864739Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: updatenotification
owncloud_1  | 2021-04-01T10:33:44.314814278Z 2021-04-01T10:33:44+00:00 Repair info: App (updatenotification) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44.314830593Z 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: user_ldap
owncloud_1  | 2021-04-01T10:33:44.315659595Z 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44.315847654Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: activity
owncloud_1  | 2021-04-01T10:33:44.315979311Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: comments
owncloud_1  | 2021-04-01T10:33:44.315992140Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: configreport
owncloud_1  | 2021-04-01T10:33:44.316052010Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: dav
owncloud_1  | 2021-04-01T10:33:44.316163590Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: federatedfilesharing
owncloud_1  | 2021-04-01T10:33:44.316176815Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: federation
owncloud_1  | 2021-04-01T10:33:44.316264492Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files
owncloud_1  | 2021-04-01T10:33:44.316405472Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_external
owncloud_1  | 2021-04-01T10:33:44.316545920Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_mediaviewer
owncloud_1  | 2021-04-01T10:33:44.316674072Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_pdfviewer
owncloud_1  | 2021-04-01T10:33:44.316857276Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_sharing
owncloud_1  | 2021-04-01T10:33:44.316870263Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_texteditor
owncloud_1  | 2021-04-01T10:33:44.317034414Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_trashbin
owncloud_1  | 2021-04-01T10:33:44.317082769Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_versions
owncloud_1  | 2021-04-01T10:33:44.317313275Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: firstrunwizard
owncloud_1  | 2021-04-01T10:33:44.319233848Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: market
owncloud_1  | 2021-04-01T10:33:44.319395228Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: notifications
owncloud_1  | 2021-04-01T10:33:44.319453729Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: provisioning_api
owncloud_1  | 2021-04-01T10:33:44.319649769Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: systemtags
owncloud_1  | 2021-04-01T10:33:44.319660323Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: templateeditor
owncloud_1  | 2021-04-01T10:33:44.319666761Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: updatenotification
owncloud_1  | 2021-04-01T10:33:44.319672842Z 2021-04-01T10:33:44+00:00 Repair info: App was not updated: user_ldap
owncloud_1  | 2021-04-01T10:33:44.744292493Z 2021-04-01T10:33:44+00:00 Repair step: Repair MySQL database engine
owncloud_1  | 2021-04-01T10:33:44.787216872Z 2021-04-01T10:33:44+00:00 Repair step: Repair MySQL collation
owncloud_1  | 2021-04-01T10:33:44.790155266Z 2021-04-01T10:33:44+00:00 Repair info: All tables already have the correct collation -> nothing to do
owncloud_1  | 2021-04-01T10:33:44.790183678Z 2021-04-01T10:33:44+00:00 Repair step: Repair SQLite autoincrement
owncloud_1  | 2021-04-01T10:33:44.790194195Z 2021-04-01T10:33:44+00:00 Repair step: Repair orphaned reshare
owncloud_1  | 2021-04-01T10:33:44.794694975Z 2021-04-01T10:33:44+00:00 Repair step: Repair duplicate entries in oc_lucene_status
owncloud_1  | 2021-04-01T10:33:44.801346594Z 2021-04-01T10:33:44+00:00 Repair info: lucene_status table does not exist -> nothing to do
owncloud_1  | 2021-04-01T10:33:44.801378629Z 2021-04-01T10:33:44+00:00 Updating database schema
owncloud_1  | 2021-04-01T10:33:44.817307557Z 2021-04-01T10:33:44+00:00 Updated database
owncloud_1  | 2021-04-01T10:33:45.005260521Z 2021-04-01T10:33:45+00:00 Repair step: Repair mime types
owncloud_1  | 2021-04-01T10:33:45.005755978Z 2021-04-01T10:33:45+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
owncloud_1  | 2021-04-01T10:33:45.005786798Z 2021-04-01T10:33:45+00:00 Repair step: Generate ETags for file where no ETag is present.
owncloud_1  | 2021-04-01T10:33:45.662885236Z 2021-04-01T10:33:45+00:00 Repair info: ETags have been fixed for 0 files/folders.
owncloud_1  | 2021-04-01T10:33:45.662958148Z 2021-04-01T10:33:45+00:00 Repair step: Clean tags and favorites
owncloud_1  | 2021-04-01T10:33:45.666331368Z 2021-04-01T10:33:45+00:00 Repair info: 0 tags of deleted users have been removed.
owncloud_1  | 2021-04-01T10:33:45.686915253Z 2021-04-01T10:33:45+00:00 Repair info: 0 tags for delete files have been removed.
owncloud_1  | 2021-04-01T10:33:45.687727203Z 2021-04-01T10:33:45+00:00 Repair info: 0 tag entries for deleted tags have been removed.
owncloud_1  | 2021-04-01T10:33:45.688396731Z 2021-04-01T10:33:45+00:00 Repair info: 0 tags with no entries have been removed.
owncloud_1  | 2021-04-01T10:33:45.688462074Z 2021-04-01T10:33:45+00:00 Repair step: Drop old database tables
owncloud_1  | 2021-04-01T10:33:45.705651487Z 2021-04-01T10:33:45+00:00 Repair step: Drop old background jobs
owncloud_1  | 2021-04-01T10:33:45.708194390Z 2021-04-01T10:33:45+00:00 Repair step: Remove getetag entries in properties table
owncloud_1  | 2021-04-01T10:33:45.709355192Z 2021-04-01T10:33:45+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
owncloud_1  | 2021-04-01T10:33:45.709423221Z 2021-04-01T10:33:45+00:00 Repair step: Repair invalid shares
owncloud_1  | 2021-04-01T10:33:45.710072411Z 2021-04-01T10:33:45+00:00 Repair step: Repair sub shares
owncloud_1  | 2021-04-01T10:33:45.710871361Z 2021-04-01T10:33:45+00:00 Repair step: Remove old share propagation app entries
owncloud_1  | 2021-04-01T10:33:45.710951282Z 2021-04-01T10:33:45+00:00 Repair step: Move user avatars outside the homes to the new location
owncloud_1  | 2021-04-01T10:33:45.711150633Z 2021-04-01T10:33:45+00:00 Repair info: No action required
owncloud_1  | 2021-04-01T10:33:45.711196424Z 2021-04-01T10:33:45+00:00 Repair step: Fix user avatars location
owncloud_1  | 2021-04-01T10:33:45.711317289Z 2021-04-01T10:33:45+00:00 Repair info: No action required
owncloud_1  | 2021-04-01T10:33:45.711432617Z 2021-04-01T10:33:45+00:00 Repair step: Remove shares of a users root folder
owncloud_1  | 2021-04-01T10:33:45.712442113Z 2021-04-01T10:33:45+00:00 Repair step: Repair unmerged shares
owncloud_1  | 2021-04-01T10:33:45.712624813Z 2021-04-01T10:33:45+00:00 Repair step: Disable extra themes
owncloud_1  | 2021-04-01T10:33:46.102772545Z 2021-04-01T10:33:46+00:00 Starting code integrity check...
owncloud_1  | 2021-04-01T10:34:09.325572302Z 2021-04-01T10:34:09+00:00 Finished code integrity check
owncloud_1  | 2021-04-01T10:34:09.551249589Z 2021-04-01T10:34:09+00:00 Update successful
owncloud_1  | 2021-04-01T10:34:09.551514807Z 2021-04-01T10:34:09+00:00 Maintenance mode is kept active
owncloud_1  | 2021-04-01T10:34:09.552004383Z 2021-04-01T10:34:09+00:00 Reset log level
owncloud_1  | 2021-04-01T10:34:10.522595688Z ownCloud is in maintenance mode - no app have been loaded
owncloud_1  | 2021-04-01T10:34:10.522636413Z
owncloud_1  | 2021-04-01T10:34:10.684303675Z ownCloud is in maintenance mode - no app have been loaded
owncloud_1  | 2021-04-01T10:34:10.684339702Z
owncloud_1  | 2021-04-01T10:34:10.693076758Z <warning>ownCloud is in maintenance mode</warning>
owncloud_1  | 2021-04-01T10:34:10.693122182Z Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call th
is script again.
owncloud_1  | 2021-04-01T10:34:10.701681113Z Writing objectstore config...
owncloud_1  | 2021-04-01T10:34:11.541658287Z Writing php config...
owncloud_1  | 2021-04-01T10:34:12.263145644Z ownCloud is in maintenance mode - no app have been loaded
owncloud_1  | 2021-04-01T10:34:12.263183266Z
owncloud_1  | 2021-04-01T10:34:12.281426250Z Updating htaccess config...
owncloud_1  | 2021-04-01T10:34:12.406154239Z ownCloud is in maintenance mode - no app have been loaded
owncloud_1  | 2021-04-01T10:34:12.406189590Z
owncloud_1  | 2021-04-01T10:34:12.414747156Z .htaccess has been updated
owncloud_1  | 2021-04-01T10:34:12.422794026Z Writing apache config...
owncloud_1  | 2021-04-01T10:34:13.017064575Z Enabling cron background...
owncloud_1  | 2021-04-01T10:34:13.142550577Z ownCloud is in maintenance mode - no app have been loaded
owncloud_1  | 2021-04-01T10:34:13.142584193Z
owncloud_1  | 2021-04-01T10:34:13.157757161Z Set mode for background jobs to 'cron'
owncloud_1  | 2021-04-01T10:34:13.165827979Z Touching cron configs...
owncloud_1  | 2021-04-01T10:34:13.219525843Z Starting cron daemon...
owncloud_1  | 2021-04-01T10:34:13.239372048Z Starting apache daemon...
owncloud_1  | 2021-04-01T10:34:13.682885778Z [Thu Apr 01 10:34:13.681818 2021] [mpm_prefork:notice] [pid 217] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
owncloud_1  | 2021-04-01T10:34:13.682932168Z [Thu Apr 01 10:34:13.681862 2021] [core:notice] [pid 217] AH00094: Command line: '/usr/sbin/apache2 -f /etc/apache2/apache2.conf -D FOREGROUND'
owncloud_1  | 2021-04-01T10:34:33.368521871Z 127.0.0.1 - - [01/Apr/2021:10:34:32 +0000] "GET /status.php HTTP/1.1" 200 1090 "-" "curl/7.68.0"
owncloud_1  | 2021-04-01T11:14:30.565472685Z 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET / HTTP/1.1" 302 1496 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Sa
fari/537.36"
owncloud_1  | 2021-04-01T11:14:30.741788755Z 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET /login HTTP/1.1" 200 2844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.
90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:31.067971276Z 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET /core/js/oc.js?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 3798 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/5
37.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:31.219960812Z 85.225.169.174 - - [01/Apr/2021:11:14:31 +0000] "GET /core/vendor/browser-update/browser-update.js?_=1617275671108 HTTP/1.1" 200 11351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:34.074440969Z 85.225.169.174 - - [01/Apr/2021:11:14:33 +0000] "POST /login HTTP/1.1" 303 788 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.
90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:34.434813485Z 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "GET /apps/files/ HTTP/1.1" 200 5490 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0
.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:35.510217766Z 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 798 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:35.515630445Z 85.225.169.174 - misse [01/Apr/2021:11:14:34 +0000] "PROPFIND /remote.php/dav/files/87bbc64e-5b02-11e9-a376-5254008c30e5/ HTTP/1.1" 207 909 "-" "Mozilla/5.0 (Macintosh) mirall/2.7.6 (build
 3261) (ownCloud, osx-18.7.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
owncloud_1  | 2021-04-01T11:14:35.928077341Z 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "PROPFIND /remote.php/dav/files/null/ HTTP/1.1" 404 769 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like
 Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:40.122421526Z 85.225.169.174 - - [01/Apr/2021:11:14:39 +0000] "REPORT /remote.php/dav/files/null/ HTTP/1.1" 404 719 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like G
ecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:42.244427376Z 85.225.169.174 - - [01/Apr/2021:11:14:41 +0000] "PROPFIND /remote.php/dav/files/null/ HTTP/1.1" 404 769 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like
 Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 2021-04-01T11:14:46.845571123Z 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /apps/files/?dir=/& HTTP/1.1" 200 5481 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chro
me/89.0.4389.90 Safari/537.36"

```

#### ownCloud log (data/owncloud.log)
```
See above
```

#### Browser log
```

a) The javascript console log
https://oc.misse.org/s/sCtgVWMNfRhumNa
b) The network log 
https://oc.misse.org/s/FP6SeTWjvPoSptu
c) ...
```
