### ISSUE TITLE
Unable to focus password input box on auth screen for a public link that is a protected share

### ISSUE THREAD

**Issue by lapsedtheorist** [owncloud/core#39103]
### Steps to reproduce
1. Create a password protected share of a directory (i.e. a public link, protected by a password)
2. Access the public link on an iPhone
3. Observe that no keyboard is available
4. Touch the password input box, to bring up the keyboard

### Expected behaviour
When the password input box is touched a keyboard should appear to allow the password to be typed.

### Actual behaviour
When the password input box is touched, observe that the form submits. On inspection (see attached screenshot) it appears that the element performing the submit is a transparent overlay over the whole password input box, thereby preventing a touch or click being used to focus the password input box. Focus can be achieved by touching or clicking on the capital "P" of the label element (i.e. the part not covered by the transparent overlay).

<img width="457" alt="Screenshot 2021-08-10 at 21 20 52" src="https://user-images.githubusercontent.com/1223963/128934216-620c4e02-3ad6-49cb-9454-6f03318689b7.png">

### Server configuration
**Operating system**:
Raspbian (Debian 10.10)
**Web server:**
nginx/1.14.2
**Database:**
mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
**PHP version:**
PHP 7.3.29-1~deb10u1
**ownCloud version:** (see ownCloud admin page)
10.8.0
**Updated from an older ownCloud or fresh install:**
Updated from previous stable version
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-latest.tar.bz2
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
The above link returns the text "No errors have been found." only

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocdhl7cw8a6y",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.8.0.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "data-fingerprint": "c74c3baa1a5532a3559c04b35056170a",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis-server.sock",
            "port": 0
        },
        "loglevel": 2,
        "theme": ""
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.8.0
    - Path: /var/www/owncloud/apps/files_external
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - gallery:
    - Version: 16.1.1
    - Path: /var/www/owncloud/apps-external/gallery
  - market:
    - Version: 0.6.1
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification
Disabled:
  - encryption:
    - Path: /var/www/owncloud/apps/encryption
  - external:
    - Path: /var/www/owncloud/apps/external
  - files_mediaviewer:
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - user_external:
    - Path: /var/www/owncloud/apps/user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local storage (USB connected)
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari on iOS 14.6, and Safari 14.1.2 on MacOS 11.5.1
**Operating system:**
as above

### Notes
I'm not convinced web server and owncloud log files are helpful in the context of this client-side rendering issue and would prefer not to share them on a public forum - please let me know if you need them and we will find a way to share them privately.
