### ISSUE TITLE
Mac OS desktop client triggers `mod_security` violations where web interface, Finder's WebDAV client, and mobile app don't

### ISSUE THREAD

**Issue by posita** [owncloud/core#39109]
### Actual behaviour
When attempting to create a new account from the [latest client](https://github.com/owncloud/client/commit/ea9d50062fe1bda7bd1b96b406519f1b6564662f) on Mac OS, I am faced with this:

![screenshot](https://user-images.githubusercontent.com/222581/129281546-0f6b4d2d-7d7c-4adc-bb2a-ecb8332d927a.png)

The following _**all**_ (still) work for the exact same user and credentials:

✅  Web
✅  Mac OS Finder's WebDAV client (⌘K from Finder)
✅  Mobile app

### Server configuration
**Operating system**: DreamHost (Ubuntu?)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**ownCloud version:** 10.8.0.4

**Updated from an older ownCloud or fresh install:** updated from 10.7.0

**Where did you install ownCloud from:** tar ball

**Signing status (ownCloud 9.0 and above):** ??? 

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "…"
        ],
        "datadirectory": "\/home\/…\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.8.0.4",
        "dbname": "…",
        "dbhost": "…",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "objectstore": {
            "class": "OCA\\Files_Primary_S3\\S3Storage",
            "arguments": {
                "bucket": "…",
                "options": {
                    "version": "2006-03-01",
                    "region": "us-west-1",
                    "credentials": {
                        "key": "***REMOVED SENSITIVE VALUE***",
                        "secret": "***REMOVED SENSITIVE VALUE***"
                    },
                    "endpoint": "http:\/\/s3.us-west-1.wasabisys.com\/",
                    "use_path_style_endpoint": true
                }
            }
        },
        "apps_paths": [
            {
                "path": "\/home\/…\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/…\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "instanceid": "oct7apj43gaw",
        "maintenance": false,
        "loglevel": 2
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity:
    - Version: 2.6.1
    - Path: .../apps/activity
  - calendar:
    - Version: 1.6.4
    - Path: .../apps-external/calendar
  - comments:
    - Version: 0.3.0
    - Path: .../apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: .../apps/configreport
  - contacts:
    - Version: 1.5.5
    - Path: .../apps-external/contacts
  - dav:
    - Version: 0.6.0
    - Path: .../apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: .../apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: .../apps/federation
  - files:
    - Version: 1.5.2
    - Path: .../apps/files
  - files_external:
    - Version: 0.8.0
    - Path: .../apps/files_external
  - files_mediaviewer:
    - Version: 1.0.4
    - Path: .../apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 0.12.2
    - Path: .../apps/files_pdfviewer
  - files_primary_s3:
    - Version: 1.1.2
    - Path: .../apps-external/files_primary_s3
  - files_sharing:
    - Version: 0.14.0
    - Path: .../apps/files_sharing
  - files_texteditor:
    - Version: 2.3.1
    - Path: .../apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: .../apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: .../apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: .../apps/firstrunwizard
  - market:
    - Version: 0.6.1
    - Path: .../apps/market
  - notifications:
    - Version: 0.5.4
    - Path: .../apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: .../apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: .../apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: .../apps/templateeditor
  - updatenotification:
    - Version: 0.2.1
    - Path: .../apps/updatenotification
Disabled:
  - admin_audit:
    - Path: .../apps/admin_audit
  - announcementcenter:
    - Path: .../apps/announcementcenter
  - customgroups:
    - Path: .../apps/customgroups
  - encryption:
    - Path: .../apps/encryption
  - enterprise_key:
    - Path: .../apps/enterprise_key
  - external:
    - Path: .../apps/external
  - files_antivirus:
    - Path: .../apps/files_antivirus
  - files_classifier:
    - Path: .../apps/files_classifier
  - files_external_dropbox:
    - Path: .../apps/files_external_dropbox
  - files_external_ftp:
    - Path: .../apps/files_external_ftp
  - files_ldap_home:
    - Path: .../apps/files_ldap_home
  - files_lifecycle:
    - Path: .../apps/files_lifecycle
  - firewall:
    - Path: .../apps/firewall
  - graphapi:
    - Path: .../apps/graphapi
  - guests:
    - Path: .../apps/guests
  - metrics:
    - Path: .../apps/metrics
  - oauth2:
    - Path: .../apps/oauth2
  - openidconnect:
    - Path: .../apps/openidconnect
  - password_policy:
    - Path: .../apps/password_policy
  - ransomware_protection:
    - Path: .../apps/ransomware_protection
  - sharepoint:
    - Path: .../apps/sharepoint
  - systemtags_management:
    - Path: .../apps/systemtags_management
  - theme-enterprise:
    - Path: .../apps/theme-enterprise
  - user_external:
    - Path: .../apps/user_external
  - user_ldap:
    - Path: .../apps/user_ldap
  - user_shibboleth:
    - Path: .../apps/user_shibboleth
  - web:
    - Path: .../apps/web
  - windows_network_drive:
    - Path: .../apps/windows_network_drive
  - wopi:
    - Path: .../apps/wopi
  - workflow:
    - Path: .../apps/workflow
```

**Are you using external storage, if yes which one:** local + S3

**Are you using encryption:** no
