### ISSUE TITLE
sharing with non-existing remote user fails silently

### ISSUE THREAD

**Issue by navid-shokri** [owncloud/core#40850]
### Steps to reproduce
1. install two instances of the Owncloud for example oc1.docker and oc2.docker
2. then share a file from oc1.docker with non existing user on the oc2.docker like "anonymous@oc2.docker"

### Expected behaviour
it should shows that the requested user is not a member of the oc2.docker

### Actual behaviour
the file is marked as a shared file with `anonymous@oc2.docker` on the sender side but on the receiving node, All behavior is Ok. (there is no record in the oc_share_external table)

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache2

**Database:**
MariaDB
**PHP version:**
7.4

**ownCloud version:** (see ownCloud admin page)
10.12.1

**Updated from an older ownCloud or fresh install:**
`fresh Install`

**Where did you install ownCloud from:**
code repository

**Signing status (ownCloud 9.0 and above):**

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'passwordsalt' => '7kDJDk9015Pt+uHlRxZeUB2hSqD5cw',
  'secret' => 'ebtv6Bla1XAusLFoUrZOLv/vf6Ghbas5VBqQoHXERzjXbo8y',
  'trusted_domains' => 
  array (
    0 => 'localhost',
      1 => 'oc1.docker',
      2 => 'oc2.docker',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '10.12.1.3',
  'dbname' => 'efss',
  'dbhost' => 'maria1.docker',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_einstein',
  'dbpassword' => 'myDBPASS',
  'allow_user_to_change_mail_address' => '',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'instanceid' => 'occyp83sq8c2',
);
```

**List of activated apps:**

```
- comments:
    - Version: 0.3.0
    - Path: /var/www/html/apps/comments
  - customgroups:
    - Version: 0.7.0
    - Path: /var/www/html/apps/customgroups
  - dav:
    - Version: 0.7.0
    - Path: /var/www/html/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/html/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/html/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/html/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/html/apps/files_external
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/html/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/html/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/html/apps/files_versions
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/html/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/html/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/html/apps/updatenotification
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**FireFox:**

**Operating system:**
Ubuntu

there is a related issue on our application that is trying to address `remote group sharing` implementation of the OCM protocol: 
https://github.com/pondersource/oc-opencloudmesh/issues/18
