### ISSUE TITLE
User logon creates exception screen - new user, never logged on, active directory user

### ISSUE THREAD

**Issue by paulgiordano** [owncloud/core#40925]
### Steps to reproduce
1. add user to owncloud
2. log in with user
3.

### Expected behaviour
Should get user's home screen

### Actual behaviour
exception screen appears

### Server configuration
**Operating system**:
Ubuntu 22.04.1
**Web server:**
apache 2.4.52
**Database:**
mysql 8.0.3
**PHP version:**
php 7.4
**ownCloud version:** (see ownCloud admin page)
10.12.2
**Updated from an older ownCloud or fresh install:**
10.12.1 (Also fails on this release)
**Where did you install ownCloud from:**
local
**Signing status (ownCloud 9.0 and above):**

```
"no errors have been found"
```
```
<?php
$CONFIG = array (
  'instanceid' => 'ociscmkfiqnf',
  'passwordsalt' => 'O9ohNfv3jRaUfmL.MkfOCQBMBij0Wm',
  'secret' => 'OPGe4pks/V3.IQ26Xp2sRqmWWtt0N.m4x6Snct21p4qTHVSw',
  'trusted_domains' =>
  array (
    0 => '10.2.0.106',
    1 => 'abtcloud',
    2 => 'abtcloud.abt.com',
    3 => 'abt-owncloud.abt.com',
    4 => '10.2.0.63',
    5 => 'abt-owncloud',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://10.2.0.63/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.12.2.1',
  'dbname' => 'ownclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ownclouduser',
  'dbpassword' => 'owncloud',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'loglevel' => 3,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => true,
  'upgrade.automatic-app-update' => true,
  'allow_user_to_change_mail_address' => '',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'password' => '',
    'dbindex' => 0,
  ),
  'mail_domain' => 'abt.com',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mailvip.abt.com.local',
  'mail_smtpport' => '25',
);
```
```
https://gist.github.com/paulgiordano/c6e38a769a23df232b1ea8b491985219.js
```

**List of activated apps:**
```
Enabled:
  - activity:
    - Version: 2.7.1
    - Path: /var/www/html/owncloud/apps/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/comments
  - configreport:
    - Version: 0.2.1
    - Path: /var/www/html/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/html/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/html/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/html/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/html/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/html/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/html/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/html/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.5.1
    - Path: /var/www/html/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/html/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/html/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/html/owncloud/apps/firstrunwizard
  - gallery:
    - Version: 16.1.2
    - Path: /var/www/html/owncloud/apps/gallery
  - market:
    - Version: 0.7.0
    - Path: /var/www/html/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/html/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/html/owncloud/apps/templateeditor
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/html/owncloud/apps/updatenotification
  - user_ldap:
    - Version: 0.17.0
    - Path: /var/www/html/owncloud/apps/user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
AD
#### LDAP configuration (delete this part if not used)
DC3.abt.com
CN=owncloud,OU=IT Services Accounts,DC=abt,DC=com,DC=local/password
DC=Abt,DC=com,DC=local
Works with older users
```
root@abtcloud:/var/www/html/owncloud# sudo -u www-data php occ ldap:show-config
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01


                                                   |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1


                                                   |
| hasPagedResultSupport         |


                                                   |
| homeFolderNamingRule          |


                                                   |
| lastJpegPhotoLookup           | 0


                                                   |
| ldapAgentName                 | CN=owncloud,OU=IT Services Accounts,DC=abt,DC=com,DC=local


                                                   |
| ldapAgentPassword             | ***


                                                   |
| ldapAttributesForGroupSearch  |


                                                   |
| ldapAttributesForUserSearch   |


                                                   |
| ldapBackupHost                |


                                                   |
| ldapBackupPort                |


                                                   |
| ldapBase                      | DC=abt,DC=com,DC=local


                                                   |
| ldapBaseGroups                | DC=abt,DC=com,DC=local


                                                   |
| ldapBaseUsers                 | DC=abt,DC=com,DC=local


                                                   |
| ldapCacheTTL                  | 600


                                                   |
| ldapConfigurationActive       | 1


                                                   |
| ldapDynamicGroupMemberURL     |


                                                   |
| ldapEmailAttribute            | mail


                                                   |
| ldapExperiencedAdmin          | 0


                                                   |
| ldapExpertGroupnameAttr       | cn


                                                   |
| ldapExpertUUIDGroupAttr       |


                                                   |
| ldapExpertUUIDUserAttr        | objectguid


                                                   |
| ldapExpertUsernameAttr        |


                                                   |
| ldapGroupDisplayName          | cn


                                                   |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=ACservice)(cn=ACstore)(cn=IT_Owncloud)(cn=InvoiceExportUsers)))     

                                                   |
| ldapGroupFilterGroups         | ACservice;ACstore;IT_Owncloud;InvoiceExportUsers


                                                   |
| ldapGroupFilterMode           | 0


                                                   |
| ldapGroupFilterObjectclass    | group


                                                   |
| ldapGroupMemberAlgo           | groupScan


                                                   |
| ldapGroupMemberAssocAttr      | member


                                                   |
| ldapHost                      | dc3.abt.com.local


                                                   |
| ldapIgnoreNamingRules         |


                                                   |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=ACservice,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14838))(|(memberof=CN=ACstore,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14837))(|(memberof=CN=IT_Owncloud,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14840))(|(memberof=CN=InvoiceExportUsers,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14973))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |


                                                   |
| ldapLoginFilterEmail          | 0


                                                   |
| ldapLoginFilterMode           | 0


                                                   |
| ldapLoginFilterUsername       | 1


                                                   |
| ldapNestedGroups              | 0


                                                   |
| ldapNetworkTimeout            | 15


                                                   |
| ldapOverrideMainServer        |


                                                   |
| ldapPagingSize                | 500


                                                   |
| ldapPort                      | 389


                                                   |
| ldapQuotaAttribute            |


                                                   |
| ldapQuotaDefault              |


                                                   |
| ldapTLS                       | 0


                                                   |
| ldapUserDisplayName           | displayname


                                                   |
| ldapUserDisplayName2          |


                                                   |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=ACservice,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14838))(|(memberof=CN=ACstore,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14837))(|(memberof=CN=IT_Owncloud,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14840))(|(memberof=CN=InvoiceExportUsers,OU=Groups,OU=Abt,DC=abt,DC=com,DC=local)(primaryGroupID=14973))))                         |
| ldapUserFilterGroups          | ACservice;ACstore;IT_Owncloud;InvoiceExportUsers


                                                   |
| ldapUserFilterMode            | 0


                                                   |
| ldapUserFilterObjectclass     | user


                                                   |
| ldapUserName                  | samaccountname


                                                   |
| ldapUuidGroupAttribute        | auto


                                                   |
| ldapUuidUserAttribute         | auto


                                                   |
| turnOffCertCheck              | 0


                                                   |
| useMemberOfToDetectMembership | 1


                                                   |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
Empty except for startup
```

#### ownCloud log (data/owncloud.log)
```
https://gist.github.com/paulgiordano/c6e38a769a23df232b1ea8b491985219.js
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) java console log
JQMIGRATE: Migrate is installed, version 1.4.0
shareconfigmodel.js?v=43be949f4d488bdc6af0255377e49fad:24  Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js?v=43be949f4d488bdc6af0255377e49fad:24:33
    at shareconfigmodel.js?v=43be949f4d488bdc6af0255377e49fad:212:3
files_mediaviewer_init.js?v=43be949f4d488bdc6af0255377e49fad:1  Uncaught TypeError: Cannot read properties of undefined (reading 'enabledPreviewProviders')
    at 473 (files_mediaviewer_init.js?v=43be949f4d488bdc6af0255377e49fad:1:115)
    at r (files_mediaviewer_init.js?v=43be949f4d488bdc6af0255377e49fad:1:1585)
    at files_mediaviewer_init.js?v=43be949f4d488bdc6af0255377e49fad:1:1823
    at files_mediaviewer_init.js?v=43be949f4d488bdc6af0255377e49fad:1:2536
b) The network log 
c) ...
```
