### ISSUE TITLE
Trusted domain environment is not getting reflected inside the config.php, docker container installation method

### ISSUE THREAD

**Issue by frisky5** [owncloud/core#40951]
### Steps to reproduce

1. setup docker-compose file to deploy owncloud server latest
2. set OWNCLOUD_TRUSTED_DOMAINS env var to ip address and deploy
3. access owncloud webpage and it shows accessing from untrusted domain
4. attach to container shell and when i check config.php it only shows localhost, neglecting the env var in docker-compose file

**_docker-compose file_**

```
version: "3"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=10.10.0.10
      - OWNCLOUD_TRUSTED_DOMAINS=10.10.0.10
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  mariadb:
    image: mariadb:10.11 # minimum required ownCloud version is 10.9
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MARIADB_AUTO_UPGRADE=1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
```

### Expected behaviour
Owncloud server shouldn't show untrusted domain

### Actual behaviour
Owncloud server show untrusted domain

### Server configuration
**Operating system**: debian bookworm with Docker version 20.10.24+dfsg1, build 297e128 

**Web server:** N/A

**Database:** mysql

**PHP version:** N/A

**ownCloud version:** latest docker image

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** docker official image

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
root@3d336ace19a9:/var/www/owncloud# cat config/config.php 
<?php
$CONFIG = array (
  'passwordsalt' => '9lMoBLMu3wGH9AFVJaZA0kC4dNDI2J',
  'secret' => 'i6daehqV7s2umXaaUAfTnWARQOUYA6JJVnRk+VTymC551toq',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/mnt/data/files',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '10.13.0.4',
  'dbname' => 'owncloud',
  'dbhost' => 'mariadb:3306',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud',
  'allow_user_to_change_mail_address' => '',
  'logtimezone' => 'UTC',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/apps-external',
      'url' => '/apps-external',
      'writable' => true,
    ),
  ),
  'installed' => true,
  'instanceid' => 'ocuthn58vicu',
);


```

**List of activated apps:**

```

```

```
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
