### ISSUE TITLE
Error: `seteuid: Operation not permitted` when starting Docker container as different user

### ISSUE THREAD

**Issue by mellertson** [owncloud/core#40977]
### Steps to reproduce

1. Copy the config files (provided below) to a Docker host machine.
2. On the Docker host machine execute the following to configure the required directories and user:
```shell script
mkdir -p /mnt/owncloud
mkdir -p /mnt/database/owncloud_mysql_data
mkdir -p /mnt/cn_data/owncloud/redis
export SERVICE_USER_ID=1005
export SERVICE_USERNAME=owncloud_server
useradd --gid 0 --no-create-home --home-dir /nonexistent --shell /usr/sbin/nologin --uid $SERVICE_USER_ID $SERVICE_USERNAME
```
3. `docker-compose build`
4. `docker-compose -f stack.localhost.yaml up`
5. Note in the console output the following error: `php_1      | seteuid: Operation not permitted`

### Expected behaviour

The Own Cloud startup scripts should change all required file permissions without error.

### Actual behaviour

As noted in the SO answer, the following error is output to the console.

```
php_1      | Waiting for Redis...
php_1      | services are ready!
php_1      | Removing custom folder...
php_1      | Linking custom folder...
php_1      | Removing config folder...
php_1      | Linking config folder...
php_1      | Writing config file...
php_1      | Skipping chown as requested...
php_1      | Skipping chmod as requested...
php_1      | Installing server database...
php_1      | ownCloud was successfully installed
php_1      | ownCloud is already latest version
php_1      | Writing objectstore config...
php_1      | Writing php config...
php_1      | Updating htaccess config...
php_1      | .htaccess has been updated
php_1      | Writing apache config...
php_1      | Enabling cron background...
php_1      | Set mode for background jobs to 'cron'
php_1      | Writing crontab file...
php_1      | Touching cron configs...
php_1      | Starting cron daemon...
php_1      | seteuid: Operation not permitted
```

### Server configuration
**Operating system**: Debian GNU/Linux 10 (buster)

**Web server:** Nginx

**Database:** mariadb:10.11

**PHP version:** Whatever version is in Docker container `owncloud/server:10.13.1-amd64`

**ownCloud version:** owncloud/server:10.13.1-amd64

**Updated from an older ownCloud or fresh install:** Fresh install using Docker.  I have included the Docker files I used when this error occurred, namely: `Dockerfile`, `docker-compose.yaml`, and `stack.localhost.yaml`

**Where did you install ownCloud from:**

The following Docker config files.

**Dockerfile**
```
FROM owncloud/server:10.13.1-amd64

# user and group IDs used to run the Docker process.
ARG SERVICE_USER=owncloud_server
ENV SERVICE_USER=${SERVICE_USER:-owncloud_server}
ARG SERVICE_GROUP=root
ENV SERVICE_GROUP=${SERVICE_GROUP:-root}
ARG SERVICE_USER_ID=1005
ENV SERVICE_USER_ID=${SERVICE_USER_ID:-1005}
ARG SERVICE_GROUP_ID=0
ENV SERVICE_GROUP_ID=${SERVICE_GROUP_ID:-0}
RUN useradd --uid ${SERVICE_USER_ID} \
--gid ${SERVICE_GROUP_ID} \
--home-dir /home/${SERVICE_USER} \
--create-home \
${SERVICE_USER}

# change ownership of Own Cloud files and directories
RUN chown -R ${SERVICE_USER}:${SERVICE_GROUP} \
/etc/cron.d \
/var/www/html \
/var/www/.cache \
/var/log/apache2 \
/var/run/apache2 \
/var/www/owncloud \
/mnt/data

USER ${SERVICE_USER}
```

**docker-compose.yaml**

```yaml
version: "3.8"

services:

  php:
    image: example.com/owncloud:10.13.1-amd64
    build:
      context: .
      dockerfile: Dockerfile
```

**stack.localhost.yaml**

```yaml
version: "3.8"

networks:
  owncloud_front:
    name: owncloud_front
  owncloud_middle:
    name: owncloud_middle
  owncloud_back:
    name: owncloud_back

services:

  php:
    image: example.com/owncloud:10.13.1-amd64
    restart: always
    user: '1005:0'
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - redis
    environment:
      OWNCLOUD_DOMAIN: example.com
      OWNCLOUD_TRUSTED_DOMAINS: example.com
      OWNCLOUD_CORS_ALLOWED_DOMAINS: example.com
      OWNCLOUD_DEFAULT_LANGUAGE: en
      OWNCLOUD_PROXY: php.owncloud.example.com:8080
      OWNCLOUD_SUB_URL: /owncloud
      OWNCLOUD_OVERWRITE_HOST: example.com
      OWNCLOUD_OVERWRITE_PROTOCOL: https
      OWNCLOUD_OVERWRITE_WEBROOT: /owncloud
      OWNCLOUD_SECRET: REDACTED
      OWNCLOUD_SKIP_CHMOD: 'true'
      OWNCLOUD_SKIP_CHOWN: 'true'
      OWNCLOUD_ADMIN_USERNAME: admin
      OWNCLOUD_ADMIN_PASSWORD: REDACTED
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: REDACTED
      OWNCLOUD_DB_HOST: db.owncloud.example.com
      OWNCLOUD_MYSQL_UTF8MB4: 'true'
      OWNCLOUD_REDIS_ENABLED: 'true'
      OWNCLOUD_REDIS_HOST: redis.owncloud.example.com
      OWNCLOUD_VERSION: 10.13
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: REDACTED
      HTTP_PORT: 8080
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      owncloud_front:
      owncloud_middle:
      owncloud_back:
      cn_jonin_front:
        aliases:
          - php.owncloud.example.com
    volumes:
      - /mnt/owncloud:/mnt/data

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: REDACTED
      MARIADB_AUTO_UPGRADE: 1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=REDACTED"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      owncloud_back:
        aliases:
          - db.owncloud.example.com
    volumes:
      - /mnt/database/owncloud_mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      owncloud_middle:
        aliases:
          - redis.owncloud.example.com
    volumes:
      - /mnt/cn_data/owncloud/redis:/data
```

**Signing status (ownCloud 9.0 and above):**

N/A

**The content of config/config.php:**

N/A

**List of activated apps:**

N/A

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** N/A

**Operating system:** N/A

#### Web server error log
```
see above
```

#### ownCloud log (data/owncloud.log)

N/A

#### Browser log

N/A
