### ISSUE TITLE
Performance degradation with shared items

### ISSUE THREAD

**Issue by lleirborras** [owncloud/core#41074]
### Steps to reproduce
1. Install Owncloud with storage over NFS
2. User A with no files / folders shared, logs in normally
3. User B shares with user A some file / folder
4. User A logs in again and owncloud tries to locate each shared fine in user A home directory, which will never find.

### Expected behaviour
The user does not experience any performance degradation after having someone else share files with that user

### Actual behaviour
User performance degrades if anyone shares files / folders with it. When performing any action , listing , showing the User avatar (https://example.com//owncloud/avatar/FOOBAR/32) , ... an extra 7 seconds or more are added , the CPU utilization increases on the server due to PHP processes. 

We cannot see any performance issue on NFS, network or any other pieces of the infrastructure. During the execution of a request, if we do an strace to the process we can see a lot of "No such file or directory" errors like this:

```
18:17:53.732790 lstat("/mnt/NFS/FOOUSERHOME/files/SharedFILE", 0x7ffe35c54df0) = -1 ENOENT (No such file or directory) <0.000066>
18:17:53.732897 lstat("/mnt/NFS/FOOUSERHOME/files", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0 <0.000031>
18:17:53.732969 lstat("/mnt/NFS/FOOUSERHOME/files/SharedFILE", 0x7ffe35c57ed0) = -1 ENOENT (No such file or directory) <0.000036>
18:17:53.733052 access("/mnt/NFS/FOOUSERHOME/files/SharedFILE", F_OK) = -1 ENOENT (No such file or directory) <0.000041>
```

where the "SharedFILE" is a file shered to FOO user, but FOOUSERHOME is the FOO user home, meaning, the file will never be there. This is happenning for each file and folder shared with the FOO user on each request. 

### Server configuration
**Operating system**: OpenSuse leap 15.5

**Web server:** Apache 2.4

**Database:** MariaDB 10.6

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) 10.13.2

**Updated from an older ownCloud or fresh install:** We have been upgrading for years, performance degradatuiob started months ago and now it's affecting users day to day

**Where did you install ownCloud from:** OpenSuse package

**Signing status (ownCloud 9.0 and above):** 

Nothing to report, it's all clean

**The content of config/config.php:**

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/srv\/www\/htdocs\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/srv\/www\/htdocs\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "instanceid": "oce06e5ec993",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/NFS",
        "dbtype": "mysql",
        "version": "10.13.2.3",
        "dbname": "owncloud",
        "dbhost": "localhost:\/run\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "maintenance": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "logfile": "\/mnt\/NFS\/logs\/owncloud.log",
        "logtimezone": "Europe\/Rome",
        "log_rotate_size": 104857600,
        "log_type": "owncloud",
        "loglevel": 1,
        "log.conditions": [
            {
                "apps": [
                    "admin_audit"
                ],
                "logfile": "\/mnt\/NFS\/logs\/admin_audit.log"
            }
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "has_internet_connection": "true",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud",
        "integrity.ignore.missing.app.signature": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "default_language": "en",
        "skeletondirectory": "\/mnt\/NFS\/skeleton",
        "singleuser": false,
        "trusted_proxies": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "metrics_shared_secret": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_mail_address": "",
        "activity_expire_days": 30
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity:
    - Version: 2.7.2
    - Path: /srv/www/htdocs/owncloud/apps/activity
  - admin_audit:
    - Version: 2.1.4
    - Path: /srv/www/htdocs/owncloud/apps/admin_audit
  - comments:
    - Version: 0.3.0
    - Path: /srv/www/htdocs/owncloud/apps/comments
  - configreport:
    - Version: 0.2.2
    - Path: /srv/www/htdocs/owncloud/apps/configreport
  - customgroups:
    - Version: 0.7.2
    - Path: /srv/www/htdocs/owncloud/apps/customgroups
  - dav:
    - Version: 0.7.0
    - Path: /srv/www/htdocs/owncloud/apps/dav
  - diagnostics:
    - Version: 0.2.0
    - Path: /srv/www/htdocs/owncloud/apps/diagnostics
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /srv/www/htdocs/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /srv/www/htdocs/owncloud/apps/federation
  - files:
    - Version: 1.6.0
    - Path: /srv/www/htdocs/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /srv/www/htdocs/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /srv/www/htdocs/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /srv/www/htdocs/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /srv/www/htdocs/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.6.0
    - Path: /srv/www/htdocs/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /srv/www/htdocs/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /srv/www/htdocs/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.3.0
    - Path: /srv/www/htdocs/owncloud/apps/firstrunwizard
  - guests:
    - Version: 0.12.3
    - Path: /srv/www/htdocs/owncloud/apps/guests
  - impersonate:
    - Version: 0.5.3
    - Path: /srv/www/htdocs/owncloud/apps/impersonate
  - metrics:
    - Version: 1.4.0
    - Path: /srv/www/htdocs/owncloud/apps/metrics
  - notifications:
    - Version: 0.6.0
    - Path: /srv/www/htdocs/owncloud/apps/notifications
  - oauth2:
    - Version: 0.6.1
    - Path: /srv/www/htdocs/owncloud/apps/oauth2
  - password_policy:
    - Version: 2.2.0
    - Path: /srv/www/htdocs/owncloud/apps/password_policy
  - provisioning_api:
    - Version: 0.5.0
    - Path: /srv/www/htdocs/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /srv/www/htdocs/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /srv/www/htdocs/owncloud/apps/templateeditor
  - theme-ifad:
    - Version: 1.0.0
    - Path: /srv/www/htdocs/owncloud/apps-external/theme-ifad
  - updatenotification:
    - Version: 0.2.1
    - Path: /srv/www/htdocs/owncloud/apps/updatenotification
  - user_ldap:
    - Version: 0.18.0
    - Path: /srv/www/htdocs/owncloud/apps/user_ldap
  - vacman-owncloud:
    - Version: 0.1.0
    - Path: /srv/www/htdocs/owncloud/apps-external/vacman-owncloud
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
LDAP configuration is correct, we have been using it for years and in multiple different applications. 
```

### Client configuration
**Browser:**
Chrome, but in general issue happens even with CURL

**Operating system:**
Widnows, but in general issue happens even with Linux and Mac OS
