### ISSUE TITLE
[QA] app dependencies are not checked during `occ upgrade`

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#41174]
Seen with files_classifier-1.5.0-rc.1

* install ownCloud 10.13.4 with files_classifier-1.4.0
* occ app:enable files_classifier
* visit admin page 'Workflow & Tasks` -> the 'Document Classification` section is there.
* occ app:list files_classifier
```
Enabled:
  - files_classifier:
    - Version: 1.4.0
    - Path: /var/www/owncloud/apps/files_classifier
```
* occ market:install -l /tmp/files_classifier-1.5.0-rc.1.tar.gz 
```
files_classifier: Installing new version from /tmp/files_classifier-1.5.0-rc.1.tar.gz
files_classifier: App updated.
```
* occ upgrade
```
...
Updating <files_classifier> ...
Updated <files_classifier> to 1.5.0
...
```
* occ app:list files_classifier
```
Enabled:
  - files_classifier:
    - Version: 1.5.0
    - Path: /var/www/owncloud/apps-external/files_classifier
```
* The app is upgraded, and seems up and running fin.
![grafik](https://github.com/owncloud/core/assets/1108546/0d95093a-8d13-405e-99ed-b3f216ec9ddf)
* nothing tells the admin, that he should have installed exiftool. BAD.
*  when a user uploads a picture. an error happens. OK
![grafik](https://github.com/owncloud/core/assets/1108546/1ce1099c-94dc-482b-8dc3-88b578e7eeb2)

----

* **But** the upload just happens, without applying any policies like triggering a workflows, or possibly getting blocked. BAD

**Comment by pako81** [comment]
`app:enable` does:
```
sudo -u www-data php occ app:enable files_classifier

In app.php line 1128:
                                                                                                                                                             
  App "Document Classification" cannot be installed because the following dependencies are not fulfilled: The command line tool exiftool could not be found  
                                                                                                                                                             

app:enable [-g|--groups GROUPS] [--] <app-id>
```

**Comment by pako81** [comment]
same as WebUI:

<img width="286" alt="Clipboard - 1  Februar 2024 16_51" src="https://github.com/owncloud/core/assets/12248713/07515f48-afa7-4191-b2f4-a41b74f4b636">

**Comment by jnweiger** [comment]
Reproducing the above steps again on a fresh system.

I can confirm, the webUI admin/apps says
![grafik](https://github.com/owncloud/core/assets/1108546/145f5742-0c80-47a7-8849-fbbf05e8192c)

But the webUI market page seems to be happy:
![grafik](https://github.com/owncloud/core/assets/1108546/9b5df8e8-2dba-415f-a962-20fc132206c7)

and so is occ app:list files_classifier:
```
Enabled:
  - files_classifier:
    - Version: 1.5.0
    - Path: /var/www/owncloud/apps-external/files_classifier
```

But yes, if the admin ignores that it is already enabled, and stubbornly tries occ app:enable files_classifier
then he sees the proper "dependencies are not fulfilled" message. But why should an admin try to enable the app that is already enabled?

I believe my scenario is not at all that unlikely.
Expected behavior: occ market:install -l should have failed with the "dependencies are not fulfilled" error message.

Adding dependencies during update did not happen often in the past. Maybe it is even the first time?
