### ISSUE TITLE
Reset password URL's protocol is "HTTP" while the site's URL has protocol "HTTPS"

### ISSUE THREAD

**Issue by sovietmir** [owncloud/core#41288]
The setup is as follows:

- Owncloud runs in a Docker container (version 10.14).
- Apache is configured as a reverse proxy to serve HTTPS requests and to redirect all HTTP requests to HTTPS.

Problematic Use Case:

1. A user browses to a login page using an HTTPS link.
2. The user enters their username and an incorrect password.
3. The system shows a "Wrong password. Reset it?" button.
4. The user clicks the button.
5. The system sends an email. In the email, there is a link to reset the password. The link has the HTTP protocol.
6. The user clicks the link.
7. The system shows the reset password page (the link was redirected to HTTPS).
8. The user enters their data and clicks "Reset password".
9. The browser blocks the request with the error: "Blocked: mixed-content".

The form that the user is submitting in step 8 has an absolute URL in the "action" attribute, and the URL uses the HTTP protocol.

Owncloud Docker Configuration:
`.env` 
```
OWNCLOUD_VERSION=10.14
OWNCLOUD_DOMAIN=localhost:8070
OWNCLOUD_TRUSTED_DOMAINS=localhost,100.100.10.5,owncloud.elru.gr
ADMIN_USERNAME=admin
ADMIN_PASSWORD=***
HTTP_PORT=8070
```
`docker-compose.yml`
```
version: "3"

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/data2tb/owncloud:/mnt/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
The configuration of MariaDB and Redis is as per the documentation.

Apache Configuration:
```
<VirtualHost *:80>
    ServerName owncloud.elru.gr
   Header set Content-Security-Policy "connect-src http://owncloud.elru.gr https://owncloud.elru.gr self; script-src http:// owncloud.elru.gr owncloud.elru.gr localhost self 'unsafe-inline'"
    Redirect permanent / https://owncloud.elru.gr/
</VirtualHost>
<VirtualHost *:443>
    ServerAdmin s97130@hotmail.com
    ServerName owncloud.elru.gr
    <IfModule mod_headers.c>
       Header set Content-Security-Policy "connect-src http://owncloud.elru.gr https://owncloud.elru.gr self; script-src http://owncloud.elru.gr owncloud.elru.gr localhost self 'unsafe-inli$
       Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>

    SSLEngine on
    SSLCertificateFile      /etc/ssl/elru.gr/elru.gr.crt
    SSLCertificateKeyFile   /etc/ssl/elru.gr/elru.gr.key
    SSLCertificateChainFile /etc/ssl/elru.gr/chain.crt

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:8070/
    ProxyPassReverse / http://127.0.0.1:8070/
</VirtualHost>
```

From the above configuration, it can be seen that the Owncloud Docker container exposes port 8070, while Apache acts as a reverse proxy and permanently redirects HTTP requests to HTTPS.
