### ISSUE TITLE
ownCloud shows wrong amount of space

### ISSUE THREAD

**Issue by MyPaperUser** [owncloud/core#41303]
### Steps to reproduce
1. Created an account with a quota of 200 GB
2. ownCloud Desktop, Mobile AND Webinterface shows a quota of 71 GB.
![image](https://github.com/user-attachments/assets/55c2ef51-eb15-4c7b-90d3-b2631daf2c1d)

### Expected behaviour
I should see 200 GB

### Actual behaviour
It says quota is 71 GB

### Server configuration
**Operating system**:

**Web server:**
Ubuntu Server 24.04
**Database:**
MySQL 15.1 Distrib 10.11.8
**PHP version:**
7.4.33
**ownCloud version:** (see ownCloud admin page)
10.14.0.3 (Webinterface says, its the newest available version)
**Updated from an older ownCloud or fresh install:**
Nearly fresh (1 month)
**Signing status (ownCloud 9.0 and above):**

_No errors have been found._

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "..."
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.14.0.3",
        "dbname": "owncloud",
        "dbconnectionstring": "",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "instanceid": "occ1rhkv109n",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_mail_address": "",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": "6379"
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**List of activated apps:**
```
Enabled:
  - activity:
    - Version: 2.7.2
    - Path: /var/www/owncloud/apps/activity
  - calendar:
    - Version: 2.0.0
    - Path: /var/www/owncloud/apps-external/calendar
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.2
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/dav
  - diagnostics:
    - Version: 0.2.0
    - Path: /var/www/owncloud/apps/diagnostics
  - extract:
    - Version: 1.3.7
    - Path: /var/www/owncloud/apps-external/extract
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.6.0
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.2
    - Path: /var/www/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_texteditor:
    - Version: 2.6.1
    - Path: /var/www/owncloud/apps/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps-external/market
  - notifications:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/notifications
  - onlyoffice:
    - Version: 9.3.1
    - Path: /var/www/owncloud/apps-external/onlyoffice
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - tasks:
    - Version: 0.9.7
    - Path: /var/www/owncloud/apps-external/tasks
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Edge
**Operating system:**
Fedora 40 KDE Plasma
#### Web server error log (Apache)
```
[Tue Aug 06 00:00:19.000196 2024] [mpm_prefork:notice] [pid 32615] AH00163: Apache/2.4.58 (Ubuntu) OpenSSL/3.0.13 configured -- resuming normal operations
[Tue Aug 06 00:00:19.000231 2024] [core:notice] [pid 32615] AH00094: Command line: '/usr/sbin/apache2'
[Tue Aug 06 02:57:14.449221 2024] [core:error] [pid 36674] [client 212.113.102.66:40804] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Tue Aug 06 04:41:07.101614 2024] [authz_core:error] [pid 37918] [client [my_ip]] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
Doesn't contain any errors

#### Browser log
Not necessary as it happens on every device
